# coding: utf-8
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
main()
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
main()
0
list[0]
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
main()
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
dfInc = main() 
plotLoop(dfInc)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfInc,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfInc,1,engine)
plotLoop(dfInc,2,engine)
plotLoop(dfInc,4,engine)
dfInc.columns()
dfInc.columns
dfMir = dfInc[dfInc['MIR'] = 'Yes']
dfMir = dfInc[dfInc['MIR'] == 'Yes']
dfMir
plotLoop(dfMir,4,engine)
plotLoop(dfMir,0,engine)
plotLoop(dfMir,10,engine)
plotLoop(dfMir,25,engine)
plotLoop(dfMir,20,engine)
plotLoop(dfMir,69,engine)
plotLoop(dfMir,77,engine)
plotLoop(dfMir,88,engine)
plotLoop(dfMir,100,engine)
plotLoop(dfMir,101,engine)
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
main()
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
datetime.time(00,00,00)
datetime.time(01,00,00)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
runfile('C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay/quantify_delay_2016.py', wdir='C:/Users/dolejar/Documents/bdit_incidents/Python/Incident Delay')
plotLoop(dfMir,102,engine)
